mutation createPurchaseMutation($userId: String!, $productId: String!) {
                        createPurchase(userId: $userId, productId: $productId) {
                            _id
                            userId
                            productId
                        }
                    }