  mutation updateUserBalanceMutation($id: String!, $balance: Int!) {
                    updateUserBalance(_id: $id, balance: $balance) {
                        _id
                        balance
                    }
                }